name: e2e-url-checker

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Go version from go.mod
        shell: bash
        run: |
          echo ::set-output name=version::$(grep '^go ' go.mod| cut -d ' ' -f 2)
        id: gomod

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ steps.gomod.outputs.version }}"

      - name: Cache go pkg
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Run URL checker tests
        run: make e2e
